name: renovatebot

on:
  schedule:
    - cron: "15 3 14,28 * *"
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovatebot-check:
    runs-on: ubuntu-24.04
    environment: security
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run renovatebot
        uses: Consensys-Incorporated/github-actions/renovatebot@89c262a30cae735be99dc776f9556b796fb456ca # main
        with:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
          GH_REPOSITORY: ${{ github.repository }}

